#!/bin/sh

CONNECT_SERVER="http://localhost:8083"

SET=N
if [ -f ../setenv ]
then
  . ../setenv
    SET=Y
fi
if [ -f ./setenv ]
then
  . ./setenv
    SET=Y
fi
if [ "$SET" = "N" ]
then
  echo;echo
  echo "Unable to find 'setenv' to set environment variables - check and rerun"
  exit 255
fi

FOUND=N
if [ "$1"x = x ]
then
  echo;echo
  echo "usage: submit jobs/XXX.json where jobs/XXX.json contains the JSON Job definition. Check and rerun"
  exit 255
fi

if [ -f $1 ]
then 
  JOB=$1
  FOUND=Y
fi
if [ -f $1.json ]
then 
  JOB=$1.json
  FOUND=Y
fi

if [ "$FOUND" = "N" ]
then
  echo;echo
  echo "usage: submit jobs/XXX.json where jobs/XXX.json contains the JSON Job definition. Check and rerun"
  echo "jobs/XXX.json not found"
  exit 255
fi


cp $JOB this.submit

COMMENTS=`cat setenv|grep "#"|wc -l|sed "s/ //g"`
if [ "$COMMENTS" = "0" ]
then
  donothing=whatKindOfCodingIsThis
else
  echo;echo;echo "setenv should only contain lines with key=value; with no comments. Check and rerun"
  exit 255
fi

JOBNAME=`echo ${JOB}|sed "s|.json||" | sed "s|jobs/||"`
cat this.submit | sed "s|REPLACEME_JOBNAME|${JOBNAME}|"  > this.submit.1 ; mv this.submit.1 this.submit

while read replaceme
do
  envvar=`echo $replaceme|awk -F= '{print $1}'`
  string=`echo $replaceme|awk -F= '{print $2}'`
  if [ ${string}x = x ]
  then
   echo;echo "${envvar} is unset! Check setenv and rerun"
   rm -f this.submit
   exit 255
  fi
  cat this.submit | sed "s/${envvar}/${string}/g" > this.submit.1 ; mv this.submit.1 this.submit
  echo ".. replaced $envvar with $string"
done < ./setenv
echo;echo "About to submit:"
cat this.submit
echo;echo;echo "Hit <return> to continue..."
read hello

echo;echo
echo ":---------------------------------:"
echo ":                                 :"
echo ":           Submitting            :"
echo ":                                 :"
echo ":---------------------------------:"
curl -X "POST" "${CONNECT_SERVER}/connectors/" -H "Content-Type: application/json" -d "$(cat this.submit)"
rm -f this.submit
